Fixes #10250 - simple SSH BMC provider
theforeman/smart-proxy pull request #278
Opened 2015-04-23 10:10 UTC by lzap

Also removed nonsense test which always fail on my configuration (I have a
different TFTP root set on my dev setup).

2015-04-23 21:27 UTC, logicminds commented
Can you provide test coverage for the new ssh provider?   What user will the ssh command login as?  If not the root user you will need to use sudo on the remote machine to run those commands.  This most likely will not work on windows and non linux hosts.  I am also wondering if we should give the ability to pass in a different ssh key file reference (use this key location instead of the default).  

On a side note I wonder if we should add support for fence agents which would provide much more coverage of various devices if needed. https://access.redhat.com/articles/28603

2016-09-20 09:41 UTC, lzap commented
Rebased, added user, individual commands configuration, tests.

2016-09-21 11:05 UTC, witlessbird commented on lib/proxy/util.rb
> +  def shell_command(cmd, wait = true)
Could you open another PR to update puppetrun providers to use this method instead the one defined in modules/puppet_proxy_common/runner.rb?

2016-09-21 11:12 UTC, witlessbird commented on test/bmc/bmc_api_ssh_test.rb
> +    Proxy::BMC::Plugin.settings.stubs(:poweron).returns('echo poweron')
Please use ```Proxy::BMC::Plugin.load_test_settings()``` instead of stubbing (less pain down the road).

2016-09-21 11:13 UTC, dmitri-d requested changes

2016-09-21 11:13 UTC, dmitri-d commented on config/settings.d/bmc.yml.example
> +#:bmc_ssh_powercycle: "shutdown -r +1"
Do all of these (`powercycle` and `poweroff` in particular) need to be settings? Can they be moved into the provider itself?

2016-09-22 08:25 UTC, lzap commented on config/settings.d/bmc.yml.example
> +#:bmc_ssh_powercycle: "shutdown -r +1"
As @logicminds stated above, there are some fencing utilities which works from shell, so you could possibly configure them here and use the ssh provider with them.

2016-09-22 08:29 UTC, lzap commented on lib/proxy/util.rb
> +  def shell_command(cmd, wait = true)
Absolutely, can you ping me after you merge this so I can fork it easily :-)

2016-09-22 09:19 UTC, lzap commented on test/bmc/bmc_api_ssh_test.rb
> +    Proxy::BMC::Plugin.settings.stubs(:poweron).returns('echo poweron')
Added.

2016-09-22 10:24 UTC, witlessbird commented
[test]

2016-09-22 14:13 UTC, dmitri-d commented
[test]

2016-09-22 14:40 UTC, witlessbird commented
Unhappy rubocop is unhappy.

2016-09-30 11:03 UTC, lzap commented
Done!

2016-10-03 10:47 UTC, witlessbird commented
Merged as d959942. Thanks, @lzap!

2016-10-03 10:47 UTC, closed without merging

2016-10-04 19:28 UTC, mmoll commented
anybody up for a corresponding PR to puppet-foreman_proxy? :)

2016-10-11 10:35 UTC, lzap commented
Michael Moll píše v Út 04. 10. 2016 v 12:28 -0700:
> anybody up for a corresponding PR to puppet-foreman_proxy? :)

I use this mainly for development, I don't see many use cases in the
production environment.

-- 
Later,
 Lukas "lzap" Zapletal