Fixes #16860 - use blank 404 page
theforeman/smart-proxy pull request #464
Opened 2016-10-11 14:14 UTC by tstrachota

2016-10-11 14:46 UTC, dmitri-d requested changes
This only fixes the issue for the root module, leaving the rest of the modules unaffected. To resolve this for all modules you'll need to change the global error handler (I think), something like: ```

```
class ::Sinatra::Base
  error Sinatra::NotFound do
   content_type 'application/json'
    [404, '']
  end
end
```

Not sure if it makes sense to return different types of content_type.

2016-10-11 15:34 UTC, tstrachota commented
@witlessbird updated

2016-10-12 09:42 UTC, witlessbird commented on lib/sinatra/default_not_found_page.rb
> +    [404, '']
We should return a brief description here, otherwise it can be hard to differentiate between a "url not found" and api "not found" errors.

2016-10-12 09:56 UTC, tstrachota commented
@witlessbird thanks, I added message `'Requested url was not found'`

2016-10-12 10:50 UTC, tstrachota commented
[test]

2016-10-12 14:35 UTC, witlessbird commented
Merged as a2b8c3b. Thanks, @tstrachota!

2016-10-12 14:35 UTC, closed without merging