Fixes #16964 - Proxy::Dns::Record#dns_find works with ipv6 params
theforeman/smart-proxy pull request #465
Opened 2016-10-17 11:46 UTC by witlessbird

2016-10-17 12:28 UTC, domcleal requested changes

2016-10-17 12:28 UTC, domcleal commented on modules/dns_nsupdate/dns_nsupdate_main.rb
>      end
Part two of the ticket was about a missing `ensure` block here, so the omshell processes were leaking. Either add it here or separate into a new ticket if you prefer.

2016-10-17 12:29 UTC, domcleal commented
I'll try and look at the test failures on Ruby 2.0/2.1, the change to CFLAGS in the latest rkerberos release isn't taking effect.

2016-10-17 12:36 UTC, witlessbird commented on modules/dns_nsupdate/dns_nsupdate_main.rb
>      end
An ensure block isn't needed for this implementation, as exception is raised before shell is spawned.

2016-10-17 12:38 UTC, witlessbird commented
Thanks, there's an update coming -- get_name can differentiate between ipv4 and ipv6 addresses. If you haven't started looking into the build failure by then, I can take a look at it.

2016-10-17 12:43 UTC, domcleal commented on modules/dns_nsupdate/dns_nsupdate_main.rb
>      end
I think it's worth adding anyway to match the create method - then if another bug occurs later, it's taken care of.

2016-10-17 13:21 UTC, witlessbird commented
- nsupdate provider now always closes om shell.
- when resolving a host name it is now possible to request ip address family.

2016-10-17 13:35 UTC, domcleal commented
[test] with rkerberos 0.1.5.

2016-10-17 14:32 UTC, domcleal commented
[test]

2016-10-17 17:36 UTC, witlessbird commented
- fixed the issue discovered by Robert Frank (pls. see http://projects.theforeman.org/issues/16964)
- fixed issues related to the one above in record collision detection methods (Proxy::DNS::Record#a_record_conflicts and Proxy::DNS::Record#aaaa_record_conflicts)

2016-10-17 20:54 UTC, witlessbird commented
The failure on ruby 2.3.0 is due to https://bugs.ruby-lang.org/issues/11910, which has been fixed in 2.3.1. We should switch to 2.3.1, as it's the stable release of 2.3.x -- I can take a look at it in the morning.

2016-10-17 21:02 UTC, mmoll commented
The reason to stay on 2.3.0 was that Ubuntu/xenial was coming with it, however, 2.3.1 is available from xenial-updates, so I'm :+1: to this, if the version requirement is bumped after merging this for xenial packages.

2016-10-18 15:07 UTC, domcleal approved these changes

2016-10-18 15:08 UTC, domcleal commented
[test] with 2.3.1.

2016-10-19 16:40 UTC, arogge commented
I'd like to suggest another change:
If `get_name(a_ptr)` used `Resolv::DNS#get_resource(ptr, Resolv::DNS::Resource::IN::PTR)` instead of `Resolv::DNS#get_name(ptr_to_ip(ptr))` you could also remove the ugly `ptr_to_ip()` as there is no need to know the IP anymore.

2016-10-20 07:35 UTC, domcleal commented
@arogge thanks, that's neater. I'd prefer to do that in a second PR though to prevent this snowballing into a refactor beyond the bug it was intended to fix.

2016-10-20 07:36 UTC, merged

2016-10-20 07:36 UTC, domcleal commented
Merged, thanks @witlessbird.