Fixes #18115 - Logger is initialized when Syslog isn't available.
theforeman/smart-proxy pull request #495
Opened 2017-01-18 14:59 UTC by witlessbird

2017-01-18 15:02 UTC, witlessbird commented
Another change is that smart-proxy exists now if syslog is configured but not available. In such a configuration ::Proxy::SETTINGS.log_file would not contain a usable path and default log file path may not be accessible to smart-proxy.

2017-01-19 09:52 UTC, domcleal requested changes

2017-01-19 09:52 UTC, domcleal commented on lib/proxy/log.rb
> +          puts "SYSLOG' logger is not supported on this platform, please use STDOUT or a file-based logger. Exiting..."
Nitpick, typo introduced with a missing single quote before "SYSLOG".

2017-01-19 10:43 UTC, witlessbird commented
Fixed the typo and rebased.

2017-01-19 10:49 UTC, domcleal approved these changes

2017-01-19 10:49 UTC, merged

2017-01-19 10:49 UTC, domcleal commented
Merged, thanks @witlessbird.