Fixes #992 - Make NFS a recognized protocol
theforeman/smart-proxy pull request #516
Opened 2017-03-28 10:27 UTC by xprazak2

Currently, if we use a medium with NFS path during provisioning, wget will fail because it cannot handle nfs.
```
16934 D, [2017-03-21T13:30:35.699595 ] DEBUG -- : Starting task: /usr/bin/wget --timeout=10 --tries=3 --no-check-certificate -nv -c "nfs://nfs-server/nfs-path/nfs-subdir/images/pxeboot      /initrd.img" -O "/var/oprazak_tftproot/boot/NFS-7-x86_64-initrd.img"
16935 I, [2017-03-21T13:30:35.699901 ]  INFO -- : 192.168.100.136 - - [21/Mar/2017 13:30:35] "POST /tftp/fetch_boot_file HTTP/1.1" 200 - 0.0013
16937 D, [2017-03-21T13:30:35.708337 ] DEBUG -- : close: 192.168.100.136:58232
16938 E, [2017-03-21T13:30:35.709638 ] ERROR -- : [15621] nfs://nfs-server/nfs-path/nfs-subdir/images/pxeboot/initrd.img: Unsupported scheme ‘nfs’.
```

This allows using NFS in semi-automatic way:

1. create a Medium: path - nfs://nfs-server/nfs-medium
2. create Operating System: name - Custom, version - 7, Architecture - x86_64, add installation medium created in previous step
3. copy images/pxeboot/initrd.img and images/pxeboot/vmlinuz from your NFS-shared medium to /var/lib/tftpboot/boot on your proxy. Make sure the newly copied files have names corresponding to your OS (Custom-7-x86_64-initrd.img and Custom-7-x86_64-vmlinuz for OS created in step 2). Files should be owned by foreman-proxy user and have 544 permissions.
4. try to provision a new host with your NFS medium. When everything is configured correctly, proxy will serve the files you just copied and installer will mount the NFS medium for installation.

2017-03-28 10:34 UTC, ekohl commented on modules/tftp/server.rb
> +      ::Proxy::LogBuffer::Decorator.instance.debug "NFS as a protocol for for installation medium detected."
for for should be for

2017-03-28 11:33 UTC, dmitri-d requested changes

2017-03-28 11:33 UTC, witlessbird commented on modules/tftp/server.rb
> +    case src.downcase.split(':').first
I think ```URI(src).scheme``` is a bit better here: if anything, no custom uri parsing and therefore no need for tests.

2017-03-28 11:33 UTC, witlessbird commented on modules/tftp/server.rb
> +      ::Proxy::LogBuffer::Decorator.instance.debug "NFS as a protocol for installation medium detected."
Please use ```logger.debug``` instead.

2017-03-28 11:34 UTC, witlessbird commented
Could you fix failing test, and add tests to verify handling of http, https, and nfs uris please?

2017-03-31 07:14 UTC, xprazak2 commented
I added tests, fixed the failing one, using `URI` and `logger.debug` now.

2017-03-31 15:03 UTC, witlessbird commented on test/tftp/tftp_test.rb
> +    Proxy::TFTP.logger.expects(:debug).once
I think the fact that we are logging at a specific level isn't important/is fragile here. I think a check that no exception is raised is in this case clearer in its intention and also less fragile.  Additionally, could add a test that verifies that an exception is raised when the url scheme isn't recognized?

2017-04-07 08:37 UTC, xprazak2 commented
I check that nothing is raised instead of expecting a debug call and I added the missing test case.

2017-04-07 10:54 UTC, merged

2017-04-07 10:55 UTC, witlessbird commented
Merged, thanks @xprazak2!