Fixes #2595 - Add more Rubyipmi methods to BMC API
theforeman/smart-proxy pull request #521
Opened 2017-04-20 18:09 UTC by Deltik

Replaces: theforeman/smart-proxy#505
Replaces: 051b285aaa9b595ea9513ff5fa197eb830b942c1

This commit implements the same features as
051b285aaa9b595ea9513ff5fa197eb830b942c1, with some differences:

 - Added unit tests for all new features
 - Added interfaces to `modules/bmc/base.rb`
 - Cleared up some ambiguous method names
 - Changed some unit test stubs to expects
 - Fixed bugs in the original implementation

New API methods:

 - GET /bmc/:host/fru
   Shows available actions: "list", "serial", "manufacturer", "model",
   and "asset_tag"

 - GET /bmc/:host/bmc
   Shows available actions: "info", "guid", and "version"

 - GET /bmc/:host/sensors
   Shows available actions: "list", "count", "names", "fanlist",
   "templist", and "get"

 - GET /bmc/:host/lan/snmp
   Shows BMC host's SNMP community string

 - GET /bmc/:host/lan/vlanid
   Shows BMC host's VLAN ID

 - GET /bmc/:host/lan/ipsrc
   Shows whether BMC host's LAN was configured "static" or "dhcp"

 - GET /bmc/:host/lan/print
   Shows BMC hosts's LAN configuration

 - PUT /bmc/:host/chassis/power/reset
   Performs power reset on chassis

 - GET /bmc/:host/fru/list
   Shows all of host's FRU information. Includes workaround for
   undocumented IBM/Lenovo IPMI bug.

 - GET /bmc/:host/fru/serial
   Shows host's serial number

 - GET /bmc/:host/fru/manufacturer
   Shows host's manufacturer

 - GET /bmc/:host/fru/model
   Shows host's product model

 - GET /bmc/:host/fru/asset_tag
   Shows host's asset tag string, if Rubyipmi has this method. It's in
   the spec, but doesn't seem to be implemented today. See spec [here](https://github.com/logicminds/rubyipmi/blob/master/spec/unit/ipmitool/fru_spec.rb).

 - GET /bmc/:host/bmc/info
   Shows information about the BMC

 - GET /bmc/:host/bmc/guid
   Shows system's GUID

 - GET /bmc/:host/version
   Shows BMC's version

 - PUT /bmc/:host/bmc/reset?type=warm
   Performs warm reset on BMC

 - PUT /bmc/:host/bmc/reset?type=cold
   Performs cold reset on BMC

 - GET /bmc/:host/sensors/list
   Shows all of host's sensors

 - GET /bmc/:host/sensors/count
   Shows number of sensors on host

 - GET /bmc/:host/sensors/names
   Shows list of sensor names on host

 - GET /bmc/:host/sensors/fanlist
   Shows all of host's fan sensors

 - GET /bmc/:host/sensors/templist
   Shows all of host's temperature sensors

 - GET /bmc/:host/sensors/get
   Shows available option "sensor" for this action

 - GET /bmc/:host/sensors/get/:sensor
   Shows information about sensor :sensor on host

2017-04-21 11:19 UTC, witlessbird commented
[test]

2017-05-04 10:06 UTC, dmitri-d requested changes

2017-05-04 10:06 UTC, witlessbird commented on modules/bmc/ipmi.rb
> +        raise 'Quirk' if frulist.empty?
I find this hard to read/follow. Can 'quirk' happen with ipmitool only? If so, why not return the error message on line 218 right away?

2017-05-04 10:06 UTC, witlessbird commented on modules/bmc/ipmi.rb
> +        rescue
The call above can throw RuntimeErrors only?

2017-05-04 10:06 UTC, witlessbird commented on modules/bmc/ipmi.rb
> +        msg = "Unknown error getting fru list."
Is this the case? Wouldn't exception contain the details of the error that caused it?

2017-05-04 10:06 UTC, witlessbird commented on modules/bmc/ipmi.rb
> +        return msg
This is also hard to follow. I'd suggest returning an error message at the top of the rescue block.

2017-05-04 17:39 UTC, Deltik commented on modules/bmc/ipmi.rb
> +        raise 'Quirk' if frulist.empty?
This has been fixed in 7fbe331.

2017-05-04 17:39 UTC, Deltik commented on modules/bmc/ipmi.rb
> +        msg = "Unknown error getting fru list."
This has been fixed in 7fbe331.  Exceptions are now returned as

> Error getting fru list: `Exception#message`

2017-05-04 17:39 UTC, Deltik commented on modules/bmc/ipmi.rb
> +        rescue
I'm catching all exceptions and feeding their messages through to the client.

2017-05-04 17:39 UTC, Deltik commented on modules/bmc/ipmi.rb
> +        return msg
This has been fixed in 7fbe331.

2017-05-05 13:35 UTC, witlessbird commented
[test]

2017-05-05 13:45 UTC, dmitri-d approved these changes

2017-05-05 13:45 UTC, witlessbird commented
Looks good, waiting for the results of the build.

2017-05-05 13:51 UTC, merged

2017-05-05 13:52 UTC, witlessbird commented
Merged, thanks @Deltik.

2017-05-05 14:01 UTC, witlessbird commented
@Deltik: did you have anything in mind re: changes to Foreman UI?

2017-05-05 15:09 UTC, Deltik commented
@witlessbird: Foreman could use this additional functionality as part of
> Foreman » Hosts » All hosts » (any host with a BMC) » BMC

![Foreman hosts BMC info](https://cloud.githubusercontent.com/assets/1364268/25751206/cedc160a-3179-11e7-8834-b43c08763c3a.png)

Currently, when showing any host with a BMC, Foreman makes these requests in the background to the associated Smart Proxy:

- `GET /bmc/BMC_IP_ADDRESS/chassis/power/status HTTP/1.1`
- `GET /bmc/BMC_IP_ADDRESS/lan/ip HTTP/1.1`
- `GET /bmc/BMC_IP_ADDRESS/lan/netmask HTTP/1.1`
- `GET /bmc/BMC_IP_ADDRESS/lan/mac HTTP/1.1`
- `GET /bmc/BMC_IP_ADDRESS/lan/gateway HTTP/1.1`

, where `BMC_IP_ADDRESS` is the IP address of the BMC.

I'm thinking there could be buttons added to fetch additional information from BMC that take longer than a few seconds, such as `GET /bmc/BMC_IP_ADDRESS/fru/list`, which takes 15 seconds for me using ipmitool and 2 seconds for me using freeipmi.

There could also be a button to fetch sensor information.  And a button to perform a BMC reset.

I haven't thought this through much, but Foreman can use these new API methods for additional BMC functionality.

---

We can also fix an issue with this:

![Foreman host power actions](https://cloud.githubusercontent.com/assets/1364268/25750644/f13ad922-3177-11e7-8166-94f93ac3d645.png)

Currently, "Cycle" means the same thing as "Reset" because they both call `PUT /bmc/BMC_IP_ADDRESS/chassis/power/cycle`, but now, "Reset" can be changed to mean `/bmc/BMC_IP_ADDRESS/chassis/power/reset`.