Fixes #6945 - use autosign path for puppetca
theforeman/smart-proxy pull request #530
Opened 2017-05-23 22:18 UTC by mmoll

2017-05-23 22:19 UTC, mmoll commented
I'm unsure about the migration and how the test for it should look like, probably I'm missing some nice helpers there?

2017-05-24 10:12 UTC, dmitri-d requested changes

2017-05-24 10:12 UTC, witlessbird commented on extra/migrations/20170523000000_migrate_autosign_setting.rb
> +  end
I can see two issues with this migration: it doesn't move unchanged config files into the destination directory (an example: https://github.com/theforeman/smart-proxy/blob/develop/extra/migrations/20161209000000_migrate_realm_settings.rb#L21), and it uses wrong directory to save the updated config file (```dst_dir``` points to the root. see https://github.com/theforeman/smart-proxy/blob/develop/extra/migrations/20161209000000_migrate_realm_settings.rb#L41 for an example).

2017-05-24 10:16 UTC, witlessbird commented
Re: migration testing. A common pattern is to test settings transformation (see https://github.com/theforeman/smart-proxy/blob/develop/test/migrations/realm_migration_test.rb for an example).

2017-05-27 21:50 UTC, mmoll commented
should be better now

2017-05-30 11:12 UTC, witlessbird commented on extra/migrations/20170523000000_migrate_autosign_setting.rb
> +        if (m == :realm) && !output[:unknown].empty?
I don't think you need this conditional at all -- I don't see remap_parameter() returning :unknown keys.

2017-05-30 11:17 UTC, mmoll commented on extra/migrations/20170523000000_migrate_autosign_setting.rb
> +        if (m == :realm) && !output[:unknown].empty?
*sigh*, I thought I had eradicated all copypastos from the realm migration... anyway, fixed.

2017-05-30 11:31 UTC, dmitri-d approved these changes

2017-05-30 12:07 UTC, merged

2017-05-30 12:08 UTC, witlessbird commented
Merged, thanks @mmoll!