Fixes #21350 - Allow restricting to TLSv1.2
theforeman/smart-proxy pull request #547
Opened 2017-10-17 02:56 UTC by ehelms

This is not the best way to do this, however, given the versions of Ruby we have to support I cannot add min_version and max_version support for multi-version support. Instead, the only way I could sumise to allow locking to TLSv1.2 or the use of both v1.1 and v1.2 was to disable TLSv1.1 if not configured.

2017-10-17 09:51 UTC, ekohl requested changes
I expect there to be an issue when TLSv1.3 comes out and a user expects to be able to disable it by setting ```ssl_versions```. Some orgs have weird middleboxes that can cause issues or reject TLSv1.3. I don't have any suggestions on how to best deal with this.

2017-10-17 09:51 UTC, ekohl commented on config/settings.yml.example
> +# TLSv1.1 and TLSv1.2 are available are the default configurations.
This is a bit hard to read. How about ```If unset the default is TLSv1.1 and TLSv1.2 when available```

2017-10-17 09:51 UTC, ekohl commented on config/settings.yml.example
> +# versions to be used. SSLv3 is disabled and cannot be configured.
s/is disabled/is always disabled/

2017-10-17 12:47 UTC, ehelms commented
Same, given the version of Ruby we have I am not sure either other than to opt for SSL version locking. That is, the user can choose TLSv1.1 or TLSv1.2 but not both. Alternatively, I just add all NO flags in and if they exist they exist.

2017-10-17 13:11 UTC, ekohl commented
Would a ```disable_ssl_versions``` config value be easier to support?

2017-10-17 13:12 UTC, ekohl commented on config/settings.yml.example
> +# versions to be used. SSLv3 is disabled and cannot be configured.
TLSv1 is also always disabled. That might be non-obvious.

2017-10-17 15:40 UTC, witlessbird commented
TLS 1.3 isn't a standard yet, we are stuck with TLS 1.2 at least for a few months. Why not mimic OpenSSL's approach and have individual setting to disable/enable specific version of TLS, i.e. ```disable_tls_1.1```?

2017-10-17 15:43 UTC, witlessbird commented
@ekohl: I think ```disable_ssl_versions``` as that would imply (to me) ssl v2 and v3, which are old and very broken and always disabled in smart-proxy.

2017-10-17 16:29 UTC, ekohl commented
> TLS 1.3 isn't a standard yet, we are stuck with TLS 1.2 for at least a few months.

Doesn't mean we can't think about it already. Our code should be future proof, especially if it's a setting. Otherwise it creates a lot of noise in the installer with migrations.

> @ekohl: I think disable_ssl_versions as that would imply (to me) ssl v2 and v3, which are old and very broken and always disabled in smart-proxy.

Somewhat true, but it's closer to the OpenSSL model. You can also document that TLSv1 and older are always disabled and don't need to be specified.

2017-10-17 17:25 UTC, witlessbird commented
I'm not sure if we need to "future-proof" something that will ever have two options, one of which isn't there yet and we don't know when it will materialize.

2018-01-03 15:44 UTC, stbenjam commented
Replaced by https://github.com/theforeman/smart-proxy/pull/559, this can be closed

2018-01-03 15:44 UTC, closed without merging