fixes #21463 - new reservations are deletable
theforeman/smart-proxy pull request #548
Opened 2017-10-25 14:27 UTC by timogoebel

This should make smart proxy detect that a record already exists when the record to be created does not have `options[:deleteable]` set.

2017-10-26 19:13 UTC, dmitri-d requested changes

2017-10-26 19:13 UTC, witlessbird commented on modules/dhcp_common/record.rb
> +      !other.nil? && self.class == other.class && ip == other.ip && mac == other.mac && subnet == other.subnet && deleteable? == other.deleteable? && options.tap { |option| option.delete(:deleteable)
This mutates both records, which it shouldn't (options hash will not contain :deleteable key if it was there before the comparison). Any reason you didn't use ```options[:deleteable] == other.options[:deleteable]``` instead?

This raises another question -- what options should be taken into account in equality comparison? For example, filename, nextserver, hostname, and a bunch of vendor-specfic options are used during record creation and were used for equality comparisons before this change.

2017-10-26 19:13 UTC, witlessbird commented on modules/dhcp_common/server.rb
> +      deleteable = to_return.delete("deleteable")
I think a better approach would be to initialize ::Proxy::DHCP::Reservation with options hash containing ```:deleteable => true```.

2017-10-26 19:13 UTC, witlessbird commented on modules/dhcp_common/record.rb
> +      !other.nil? && self.class == other.class && ip == other.ip && mac == other.mac && subnet == other.subnet && deleteable? == other.deleteable? && options.tap { |option| option.delete(:deleteable)
Considering that we assume that reservations are always deleteable, and if we make them so by default (pls. see my comment below), I don't think this change is needed at all.

2017-10-27 08:58 UTC, timogoebel commented
@witlessbird: Thanks. I think I addressed all your comments. All reservations now default to being deletable.

2017-10-27 17:45 UTC, witlessbird commented on modules/dhcp_common/record/reservation.rb
>        super(ip_address, mac_address, subnet, options)
You could avoid modifying the options hash by doing something like:
```
super(ip_address, mac_address, subnet, {:deleteable => true}.merge(options))
```

2017-10-27 17:53 UTC, witlessbird commented
There's an issue specific to isc dhcpd: all reservations are now deletable by default, while in actuality only "dynamic" ones are. 

One of the ways to handle this is to change how Proxy::DHCP::Reservation options are initialized. Adding :deleteable => false to the initial hash here: https://github.com/theforeman/smart-proxy/blob/develop/modules/dhcp_common/isc/subnet_service_initialization.rb#L96 would resolve this -- dynamic reservations have :deleteable key set to true.

2017-11-01 12:15 UTC, timogoebel commented
@witlessbird: Thanks for the hint. Added the missing default parameter and some tests to cover that.

2017-11-01 18:54 UTC, witlessbird commented on modules/dhcp_common/record/reservation.rb
>        super(ip_address, mac_address, subnet, options)
Not sure if you missed this -- could you change how "deleteable" option is initialized?

2017-11-01 18:55 UTC, witlessbird commented
Could fix the tests please?

2017-11-06 08:55 UTC, timogoebel commented
@witlessbird: Sorry for the delay. Fixed the tests.

2017-11-06 15:49 UTC, witlessbird commented
[test]

2017-11-06 19:36 UTC, witlessbird commented
Could you update the constructor here: https://github.com/theforeman/smart-proxy/pull/548/files#diff-86d12e513b5cb76326d7322cd5aa0f35R10 to not modify the parameters that passed into it?

2017-11-06 19:57 UTC, witlessbird commented
[test]

2017-11-06 20:30 UTC, timogoebel commented
@witlessbird: Omg, what am I doing here? Addressed your comment, sorry. I missed that. Twice. :-/

2017-11-06 22:28 UTC, merged

2017-11-06 22:28 UTC, witlessbird commented
Merged, thanks @timogoebel!

2017-11-07 08:47 UTC, timogoebel commented
@witlessbird: Thanks for your help with this.
Do you want to put this on 1.16 or 1.17?

2017-11-07 17:26 UTC, witlessbird commented
@timogoebel: This has a potential to break stuff; unless someone specifically asked for this fix in the stable branch, I'd like to keep it out of it.

2017-12-14 13:07 UTC, lzap commented on modules/dhcp_common/record/reservation.rb
> +      super(ip_address, mac_address, subnet, {:deleteable => true}.merge(options))
I don't know why but this line created regression from 1.16 which I reported here: http://projects.theforeman.org/issues/21975

2017-12-14 13:11 UTC, lzap commented
Indeed, in develop "filename" options are no longer stored and completely ignored. Not sure why, can you guys take a look please?