add support for srv dns records
theforeman/smart-proxy pull request #577
Opened 2018-04-24 15:40 UTC by pronix

2018-04-24 15:47 UTC, ekohl requested changes
This makes sense.

2018-04-24 15:47 UTC, ekohl commented on modules/dns/dns_api.rb
> +        weight.to_i >= 0 and
Both weight and priority have a rage of 0-65535 according to [RFC2782](https://tools.ietf.org/html/rfc2782)

2018-04-24 15:47 UTC, ekohl commented on modules/dns/dns_api.rb
> +        validate_dns_name!(fqdn) if type != 'SRV'
If it's SRV, we can still validate it if we allow underscores. It'd be good to have this validation both here and below.

2018-04-24 16:22 UTC, pronix commented on modules/dns/dns_api.rb
> +        validate_dns_name!(fqdn) if type != 'SRV'
but underscore is not allowed for fqdn.

2018-04-24 16:25 UTC, ekohl commented on modules/dns/dns_api.rb
> +        validate_dns_name!(fqdn) if type != 'SRV'
I meant that you should split the validation. Roughly like this:
```ruby
if type == 'SRV'
  validate_srv_name!(fqdn)
else
  validate_dns_name!(fqdn)
end
```

2018-04-24 17:02 UTC, pronix commented
@ekohl fixes pushed.

2018-04-24 17:09 UTC, ekohl commented on modules/dns/dns_api.rb
> +      priority,weight,port,target = value.split(' ')
Not an expert on ruby, but you probably need to ensure that it also handles values where it isn't 4. Could you write tests for this function?

2018-04-24 17:54 UTC, pronix commented
@ekohl  added check for extra data and test for it.

2018-04-24 18:08 UTC, ekohl commented
@pronix thanks! Could you also add an example with too little values or incorrect types like a letter for a priority instead of a number?

2018-04-24 18:15 UTC, pronix commented
@ekohl added more tests and more checks, letter for priority was missed.

2018-04-24 19:06 UTC, dmitri-d requested changes

2018-04-24 19:06 UTC, dmitri-d commented on modules/dns/dns_api.rb
> +        if type == 'SRV'
To reduce duplication, could you move the conditional inside ```validate_dns_name!```, but perhaps keep type-specific validation in dedicated methods?

2018-04-24 19:06 UTC, dmitri-d commented on test/dns/dns_api_test.rb
> +  def test_create_srv_record_returns_error_if_value_is_wrong2
Could you convert this test and the other two below to unit-tests that exercise the validator directly? They'd be clearer/easier to follow and more helpful in troubleshooting.

2018-04-24 19:06 UTC, dmitri-d commented on test/dns/dns_api_test.rb
> +  def test_create_srv_record_returns_error_if_value_is_wrong3
ditto

2018-04-24 19:06 UTC, dmitri-d commented on modules/dns/dns_api.rb
> +      raise Proxy::Dns::Error.new("Invalid DNS SRV value #{value}") unless priority.scan(/\D/).empty? and
Could you replace ```and``` with ```&&``` and convert this expression to an ```if ... end``` form.

2018-04-24 19:06 UTC, dmitri-d commented on modules/dns/dns_api.rb
> +      raise Proxy::Dns::Error.new("Invalid DNS SRV value #{value}") unless priority.scan(/\D/).empty? and
What's the purpose of ```nillval```? To verify that the input string has been split into a correct number parts? If so, I'd do something like this instead:

```
parts = value.split(' ')
raise "!!!" if parts.size != 4
```

As it's clearer/more explicit.

2018-04-24 19:06 UTC, dmitri-d commented on modules/dns/dns_api.rb
> +        weight.scan(/\D/).empty? and
Instead of doing a regex check followed by a conversion, you can do ```Integer(weight)```, which will do both. You still need to do a range check however.

2018-04-24 19:15 UTC, closed without merging

2018-05-01 20:43 UTC, jewgeni-prokhorenko commented
I'm on it.

2018-05-02 18:21 UTC, eugen-berlin commented
See #582.