add support for srv dns records
theforeman/smart-proxy pull request #582
Opened 2018-05-02 18:20 UTC by jewgeni-prokhorenko

Here are original changes made by @pronix from #577 + fixes suggested by @witlessbird. Except I didn't change API tests to unit tests - I didn't understand how it should look like in the end. Do you mean to just test methods that validate records? Because we have no separate validator there.

2018-05-02 19:05 UTC, dmitri-d commented
@jewgeni-prokhorenko cheers for the PR.

> Do you mean to just test methods that validate records? Because we have no separate validator there.

You could invoke ```validate_srv_value!``` and ```validate_srv_name!``` directly in tests, as opposed to calling the top-level methods in the api controller. This would result in clearer tests and would help with maintenance down the road (tests written in this fashion tend to break less).

2018-05-05 18:29 UTC, jewgeni-prokhorenko commented
@witlessbird please review - I added a commit that replaces the current way of testing with unit tests.

2018-05-07 10:28 UTC, ekohl requested changes

2018-05-07 10:28 UTC, ekohl commented on modules/dns/dns_api.rb
> +    def validate_dns_name!(name, type)
The function remains compatible if you use `type=nil`. Not sure if plugins use this function.

2018-05-07 10:28 UTC, ekohl commented on test/dns/dns_api_test.rb
> +  def test_validate_srv_name!
Could you add a test for `_sip._tcp.example.com`?

2018-05-07 10:50 UTC, jewgeni-prokhorenko commented
added test and made `validate_dns_name!` backwards compatible

2018-05-07 14:00 UTC, ekohl commented
ok to test

2018-05-07 17:49 UTC, witlessbird commented on test/dns/dns_api_test.rb
> +  end
Coud you either split this test into three or add comments about why exceptions are expected to be raised? The former is a better way to go about it.

2018-05-07 17:51 UTC, witlessbird commented
@jewgeni-prokhorenko, thanks for the changes, looks good other than one nitpick I mentioned.

2018-05-07 18:19 UTC, jewgeni-prokhorenko commented
@witlessbird thank you very much for your suggestions

2018-05-07 19:12 UTC, witlessbird commented
These changes look good, but I originally meant the test here: https://github.com/theforeman/smart-proxy/pull/582/files#diff-cdb8479e65c28a30d109362f98c679baR238. 

FWIW the reason I'm being picky is that one assertion per test-type tests are easier to live with down the line. When they fail it's immediately clear why, and a good description of the test helps to understand the root-cause.

2018-05-07 21:06 UTC, jewgeni-prokhorenko commented
@witlessbird understandable - please see the new commit

2018-05-07 22:12 UTC, witlessbird commented
[test]

2018-05-07 23:13 UTC, witlessbird commented
Rubocop isn't happy.

here: https://github.com/theforeman/smart-proxy/pull/582/files#diff-c603a2778d38b35e4c4c3f5a1edc6d35R86 -- could you either disable the rubocop check, or replace ```===``` with ```cover?```.
On the same lines, could separate each three orders of magnitude in all integer constants with a ```_```, e.g. ```123456789``` becomes ```123_456_789```.

2018-05-08 07:31 UTC, jewgeni-prokhorenko commented
fixed

2018-05-08 15:41 UTC, witlessbird commented
[test]

2018-05-09 13:41 UTC, jewgeni-prokhorenko commented
Hello colleagues. Can this pull request be merged now? Tests and code style checks are in order.

2018-05-09 18:42 UTC, witlessbird commented
I'm getting 

```
D, [2018-05-09T11:25:16.350171 ] DEBUG -- : undefined local variable or method `fqdn' for #<Proxy::Dns::Nsupdate::Record:0x00000004640ab0> (NameError)
/home/wb/sandbox/smart-proxy/modules/dns_common/dns_common.rb:80:in `remove_srv_record'
/home/wb/sandbox/smart-proxy/modules/dns/dns_api.rb:71:in `block in <class:Api>'
```

when attempting to delete an ```SRV``` record: ```Proxy::Dns::Record#remove_srv_record``` method doesn't have ```fqdn``` parameter. 

Also, could you add test(s) for ```SRV``` record removal please?

2018-05-09 19:28 UTC, witlessbird commented
[test]

2018-05-09 19:30 UTC, jewgeni-prokhorenko commented
@witlessbird thank you

"The elephant was what I didn't notice." -- Ivan Krylov :)

2018-05-09 20:49 UTC, witlessbird commented
@jewgeni-prokhorenko: could you rebase and squash commits please?

2018-05-09 21:27 UTC, eugen-berlin commented
@witlessbird rebased & squashed

2018-05-09 22:42 UTC, witlessbird commented
[test]

2018-05-09 22:44 UTC, witlessbird commented
There are still two commits here, could you squash it to one please? Otherwise this can potentially cause problems during cherry-picking and such.

2018-05-10 09:33 UTC, jewgeni-prokhorenko commented
@witlessbird squashed

2018-05-10 10:20 UTC, mmoll commented
[test]

2018-05-10 16:59 UTC, merged

2018-05-10 16:59 UTC, witlessbird commented
Merged, thanks @jewgeni-prokhorenko, @pronix.