Fixes #24364 - non-ascii logs are readable now
theforeman/smart-proxy pull request #596
Opened 2018-07-24 08:14 UTC by lzap

Logs API is unable to return binary/malformed UTF strings which can end up in logs when request line is incorrect.

1) Start a proxy (upstream develop branch is affected as well):
2) Have "logs" module enabled
3) Send arbitrary binary data via TCP plain connection to HTTP endpoint: nc localhost 8448 < /usr/bin/bash
4) Call logs API: curl-proxy /logs

```
D, [2018-07-24T09:58:14.814774 ] DEBUG -- : "\xB0" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
/home/lzap/work/smart-proxy/modules/logs/logs_api.rb:15:in `encode'
/home/lzap/work/smart-proxy/modules/logs/logs_api.rb:15:in `to_json'
/home/lzap/work/smart-proxy/modules/logs/logs_api.rb:15:in `block in <class:LogsApi>'
```

The fix is simple - we convert into UTF-8 earlier replacing all invalid characters with `?`.

2018-07-25 08:57 UTC, adamruzicka requested changes
Fixes the issue for me, but it seems test failures are related

2018-07-26 09:48 UTC, lzap commented
Corrected, thanks.

2018-07-26 11:15 UTC, adamruzicka approved these changes
Test failure unrelated, ACK

2018-07-26 12:40 UTC, lzap commented
Thanks [test] it was an issue on Jenkins perhaps.

2018-07-27 08:56 UTC, dLobatog approved these changes
Thanks @lzap & @adamruzicka !

2018-07-27 08:56 UTC, merged

2018-07-27 08:56 UTC, dLobatog commented
Should this make 1.18.1/1.19? I'd say yes

2018-07-27 11:20 UTC, lzap commented
Yes thanks, CPs are all pending, I set RM FIV as well.