Fixes #23353 - included DHCP files default directory
theforeman/smart-proxy pull request #600
Opened 2018-08-01 04:34 UTC by slueder

Hi All,

sorry for the long delay in coming back to you about this topic.
Lukas, thank you very much for the comments and recommendations about the previous pull request.

Please find attached the changes to the files as recommended by Lukas.

There is one exception and I need your support / discuss this with you:
Using an instance variable (@config_path) instead of a class variable (@@config_path) in   modules/dhcp_common/isc/configuration_parser.rb doesn't work

It seems as the parser framework uses different class instances when doing the parsing.
Thus when using instance variable @config_path the tests fail with 
  => 479:     included = Proxy::DHCP::CommonISC::ConfigurationParser.new.subnets_hosts_and_leases(File.read('test/fixtures/dhcp/dhcp_include_relative_testcase1.conf'), 'test/fixtures/dhcp/dhcp_include_relative_testcase1.conf').flatten
... (omitted) ...
Error: test_include_relative(Proxy::DHCP::CommonISC::ConfigurationParserTest): Errno::ENOENT: No such file or directory @ rb_sysopen - dhcp_subnets.conf

So i left the class variable in the code.
Please let me know, if this is acceptable or if there is an alternate approach better suitable.

Thanks
Sven

2018-08-02 21:27 UTC, mmoll commented
continuation of GH-593

2018-08-02 21:28 UTC, mmoll commented
ok to test

2018-08-09 11:34 UTC, lzap commented
Thanks, I still see you used `slueder:develop` branch, you usually want to create "topic git branch" before you do PR, now it will be slightly harder for you to update the develop branch after this is merged. Simply do `git reset --hard HEAD^^^^^^^^` *AFTER* this PR is merged and then you can do `git pull` normally to pull your changes. Remember to create "topic branch" before starting working on anything! :-)

Now to the review.

2018-08-09 12:02 UTC, lzap commented
@witlessbird do you have a minute? I can see that we send filename via "source" rsec option (`conf.parse!(conf_as_string, filename)`) and it looks like it stores it into some context. Do you know if this context is available in our parsing code so we can reach the "source" attribute in `include_file` method?

https://github.com/luikore/rsec/blob/master/lib/rsec/parser.rb#L16

2018-08-09 12:04 UTC, lzap requested changes
Other than that, nicely done thanks. Let's try @witlessbird if he has an idea how to access the required base filename path.

2018-08-09 12:04 UTC, lzap commented on Gemfile
> +
Please remove extra line from here. (Just add new commit on top of the two I will squash them during merge).

2018-08-09 12:04 UTC, lzap commented on modules/dhcp_common/isc/configuration_parser.rb
> +          @@config_path = File.dirname(filename)
This is really bad hack, we need to figure it out. Asked Dmitri who wrote the parser, I am not sure how to properly access it.

2018-08-11 04:09 UTC, witlessbird commented
@lzap: ParseContext is used to keep parsing state/error reporting; I doubt it's reachable from nodes in the parse tree.

2018-08-13 09:25 UTC, lzap commented
Thanks Dmitri. This confirms my impression so far.

@slueder we can't use class-level variable because this is not thread-safe. But we can use ConfigurationParser instance, I am not sure why new instance was created for each file included. Here is a change which works for me. Also I break your test into two separate ones just for better clarity:

```diff
diff --git a/modules/dhcp_common/isc/configuration_parser.rb b/modules/dhcp_common/isc/configuration_parser.rb
index 54cbf1b..a31a99b 100644
--- a/modules/dhcp_common/isc/configuration_parser.rb
+++ b/modules/dhcp_common/isc/configuration_parser.rb
@@ -397,7 +397,7 @@ module Proxy
           Rsec::Fail.reset
           include_keyword = word('include').fail 'include_keyword'
           seq_(include_keyword, literal) do |_, filename_in_quotes|
-            ConfigurationParser.new.parse_file(literal_to_filename(filename_in_quotes))
+            parse_file(literal_to_filename(filename_in_quotes))
           end
         end
 
@@ -405,7 +405,8 @@ module Proxy
            a_literal[1..-2]
         end
 
-        def conf
+        def conf(config_basedir = nil)
+          @config_basedir = config_basedir
           SPACE.join(option | host | lease | group | subnet | shared_network | include_file | COMMENT | server_duid | ignored_declaration | ignored_block | EOSTMT).odd.eof
         end
 
@@ -427,16 +428,14 @@ module Proxy
         end
 
         def parse_file(a_path)
-          if defined? @@config_path
-            a_path = File.absolute_path(a_path, @@config_path)
-          end
+          a_path = File.absolute_path(a_path, @config_basedir) unless @config_basedir.nil?
           File.open(a_path, 'r:ASCII-8BIT') {|f| conf.parse!(f.read, a_path)}
         end
 
         # returns all_subnets, all_hosts, root_group
         def subnets_hosts_and_leases(conf_as_string, filename)
-          @@config_path = File.dirname(filename)
-          parsed = conf.parse!(conf_as_string, filename)
+          config_basedir = File.dirname(filename)
+          parsed = conf(config_basedir).parse!(conf_as_string, filename)
           start_visiting_parse_tree_nodes(parsed)
         end
       end
diff --git a/test/dhcp/conf_parser_test.rb b/test/dhcp/conf_parser_test.rb
index c5c6ca2..746e077 100644
--- a/test/dhcp/conf_parser_test.rb
+++ b/test/dhcp/conf_parser_test.rb
@@ -475,11 +475,14 @@ OFMULTILNE_LEASE
                  included.select {|node| node.class == Proxy::DHCP::CommonISC::ConfigurationParser::HostNode}.map(&:fqdn)
   end
 
-  def test_include_relative
-    included = Proxy::DHCP::CommonISC::ConfigurationParser.new.subnets_hosts_and_leases(File.read('test/fixtures/dhcp/dhcp_include_relative_testcase1.conf'), 
+  def test_include_relative_case1
+    included = Proxy::DHCP::CommonISC::ConfigurationParser.new.subnets_hosts_and_leases(File.read('test/fixtures/dhcp/dhcp_include_relative_testcase1.conf'),
                                                                                         'test/fixtures/dhcp/dhcp_include_relative_testcase1.conf').flatten
     assert_equal ['test.example.com'],
                  included.select {|node| node.class == Proxy::DHCP::CommonISC::ConfigurationParser::Host}.map(&:name)
+  end
+
+  def test_include_relative_case2
     included = Proxy::DHCP::CommonISC::ConfigurationParser.new.subnets_hosts_and_leases(File.read('test/fixtures/dhcp/dhcp_include_relative_testcase2.conf'),
                                                                                         'test/fixtures/dhcp/dhcp_include_relative_testcase2.conf').flatten
     assert_equal ['test.example.com'],
```

2018-12-18 17:54 UTC, mmoll commented
@slueder What's the status here?

2018-12-19 15:52 UTC, lzap commented
@slueder please apply my patch on top of your work, rebase and we are good to go!

2019-01-06 23:18 UTC, mmoll commented
continuation in GH-627, thanks @slueder for the patch!

2019-01-06 23:18 UTC, closed without merging