refs #23211 - make PuppetCA token provider more resilient
theforeman/smart-proxy pull request #607
Opened 2018-09-14 09:37 UTC by timogoebel

2018-09-14 09:54 UTC, timogoebel commented
This fixes three issues I found with the current implementation:

* The helper script calls the wronmg URL. Bummer.
* The autosigner implementation for `#disable` needs to return `nil`.
* The `certificate` setting is `nil` by default. If we specify this explicitly smart-proxy treats it as a required parameter.

2018-09-14 12:40 UTC, timogoebel commented
@ekohl: Can you review and merge?

2018-09-19 09:55 UTC, juliantodt requested changes
Nice catches! Thanks for the fixes. While you're at it, could you also change https://github.com/theforeman/smart-proxy/blob/develop/modules/puppetca_token_whitelisting/puppetca_token_whitelisting_autosigner.rb#L10 to an Integer as this currently breaks the certificate generation?

2018-09-19 09:55 UTC, juliantodt commented on extra/puppet_sign.rb
> +uri              = URI.parse("#{protocol}://#{fqdn}:#{port}/puppet/ca/verify")
This should be `/puppet/ca/validate`. See https://github.com/theforeman/smart-proxy/blob/develop/modules/puppetca/puppetca_api.rb#L40

2018-09-19 10:15 UTC, timogoebel commented
@juliantodt: Fixed your comments. Can you ack now?

2018-09-19 10:16 UTC, juliantodt approved these changes

2018-09-19 10:21 UTC, timogoebel commented
@lzap: Do you mind doing a quick merge? This fixes some issues we found when testing this in a production deployment.

2018-09-21 07:41 UTC, lzap approved these changes
I am good thanks.

2018-09-21 07:41 UTC, lzap commented on extra/puppet_sign.rb
> +uri              = URI.parse("#{protocol}://#{fqdn}:#{port}/puppet/ca/validate")
This is quite a change I can hardly comment but this looks like some `extra` script.

2018-09-21 07:41 UTC, merged

2018-09-21 07:41 UTC, lzap commented
There you have it! Thanks.