Anonymise organisation specific server references in tests/dhcp
theforeman/smart-proxy pull request #674
Opened 2019-08-17 04:00 UTC by ndietsch

There are server organisation specific server references in these files and I have anonymised them. Sorry for any noise created during the commit process.

2019-08-17 07:17 UTC, ekohl requested changes
Thanks! I'd noticed we had a few of these instances as well. Could you also squash your commits into one?

2019-08-17 07:17 UTC, ekohl commented on test/dhcp/isc_omapi_provider_test.rb
> +      %q{option SUNW.install-server-hostname \"someserver.somedomain\";},
It's common to use example.(com|org|net) for this.

2019-08-18 23:19 UTC, ndietsch commented
Hi,

 
I will resubmit it as a single example.com commit. 

 
Thanks,

 
Nathan 

-----Original message-----
From: Ewoud Kohl van Wijngaarden
Sent: Saturday, August 17 2019, 2:17 am
To: theforeman/smart-proxy
Cc: Nathan Dietsch; Author
Subject: Re: [theforeman/smart-proxy] Anonymise organisation specific server references in tests/dhcp (#674)

@ekohl requested changes on this pull request.

Thanks! I'd noticed we had a few of these instances as well. Could you also squash your commits into one?

--------------------------------
In test/dhcp/isc_omapi_provider_test.rb:


> @@ -105,10 +105,10 @@ def test_sparc_host_quirks
     assert_equal [
       %q{option SUNW.JumpStart-server \"192.168.122.24:/Solaris/jumpstart\";},
       %q{option SUNW.install-path \"/Solaris/install/Solaris_5.10_sparc_hw0811\";},
-      %q{option SUNW.install-server-hostname \"itgsyddev807.macbank\";},
+      %q{option SUNW.install-server-hostname \"someserver.somedomain\";},


It's common to use example.(com|org|net) for this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-08-19 05:24 UTC, ndietsch commented
Hi,

 
The pull request has been resubmitted as a single commit and I updated the references to example-server.example.com

 
Kind Regards,

 
Nathan Dietsch 

-----Original message-----
From: Nathan Dietsch
Sent: Sunday, August 18 2019, 6:19 pm
To: theforeman/smart-proxy
Subject: RE: [theforeman/smart-proxy] Anonymise organisation specific server references in tests/dhcp (#674)

Hi,

 
I will resubmit it as a single example.com commit. 

 
Thanks,

 
Nathan 

-----Original message-----
From: Ewoud Kohl van Wijngaarden
Sent: Saturday, August 17 2019, 2:17 am
To: theforeman/smart-proxy
Cc: Nathan Dietsch; Author
Subject: Re: [theforeman/smart-proxy] Anonymise organisation specific server references in tests/dhcp (#674)
 
@ekohl requested changes on this pull request.

Thanks! I'd noticed we had a few of these instances as well. Could you also squash your commits into one?

--------------------------------
In test/dhcp/isc_omapi_provider_test.rb:


> @@ -105,10 +105,10 @@ def test_sparc_host_quirks
     assert_equal [
       %q{option SUNW.JumpStart-server \"192.168.122.24:/Solaris/jumpstart\";},
       %q{option SUNW.install-path \"/Solaris/install/Solaris_5.10_sparc_hw0811\";},
-      %q{option SUNW.install-server-hostname \"itgsyddev807.macbank\";},
+      %q{option SUNW.install-server-hostname \"someserver.somedomain\";},


It's common to use example.(com|org|net) for this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-08-19 07:17 UTC, lzap commented
Ok you could have force-pushed here but this is fine.

2019-08-19 07:17 UTC, closed without merging