Fixes #32607 - drop host from x-forwarded-for
theforeman/smart-proxy pull request #790
Opened 2021-05-17 12:48 UTC by lzap

We do not use this at all.

2021-05-17 13:18 UTC, ekohl requested changes
Last Friday I tried to read up on this and it's my reading that this is correct, just a minor inline code suggestion.

It would be even more correct to see if there already was a `X-Forwarded-For` header. If so, send that together with `REMOTE_ADDR`. Respecting `X-Forwarded-For` could be considered a feature though.

This might need a cherry pick into stable branches. If so, I'd limit the cherry pick to just what this PR is (the bugfix) and open a new PR for the feature.

2021-05-17 13:18 UTC, ekohl commented on modules/templates/proxy_request.rb
> +      proxy_headers["X-Forwarded-For"] = "#{env['REMOTE_ADDR']}"
```suggestion
      proxy_headers["X-Forwarded-For"] = env['REMOTE_ADDR']
```

2021-06-23 12:10 UTC, lzap commented
Yeah sorry, rebased and amended the change. Since this is an important bug, I want just to fix this.

Introducing passing already-forwarded entries might actually trigger the bug we have in Foreman too, so that needs probably more work.

2021-06-24 09:34 UTC, ekohl approved these changes
Thanks!

2021-06-24 09:35 UTC, ekohl requested changes
Apologies, test failures are related.

2021-08-20 08:50 UTC, lzap commented
For the record I asked one of our users to test this patch in https://community.theforeman.org/t/foreman-2-4-katello-4-ipxe-not-working/23398/45

2021-08-26 15:35 UTC, Thulium-Drake commented
As also mentioned on the forum, this patch in combination with an edit of the ```foreman_proxies``` works like a charm:

```
# /etc/foreman/settings.yaml
# ... existing config
:trusted_proxies:
  - "127.0.0.0/8"
  - "::1"
  - "<IP address of the foreman server>"
```

2021-08-26 15:36 UTC, Thulium-Drake approved these changes

2021-08-26 15:57 UTC, ekohl commented
> Apologies, test failures are related.

This is still true. The actual change looks good, but I don't want to break the build.

2021-09-01 11:37 UTC, lzap commented
Fixed tests, rebased.

2021-09-01 11:38 UTC, ekohl approved these changes

2021-09-01 11:40 UTC, merged

2021-09-09 23:15 UTC, Thulium-Drake commented
One addition, you also need to put _all_ smart proxy IPs on the same ```trusted_proxies``` list, if you don't you get 500 errors on the client. And 409 conflicts on the Foreman server (not the proxy)